### ISSUE TITLE
Push tags to github

### ISSUE THREAD

**Issue by dkhunt27** [darsain/grunt-tagrelease#1]
Does the grunt package push the tags to github?  It doesn't appear to be doing that for me.  If I run git push --tags, then it pushes all the tags.

Is this by design?

Thanks,
Dan

**Comment by darsain** [comment]
The task doesn't do `push`, nor `push --tags`, as I didn't know how to handle prompts for password, or setting the ssl from within the task :) It seemed overly complicated.

Also, I want to do those things manually, because I want to check that tasks did what they were supposed to, there were no errors, and everything is all right before I push stuff. But the reason in first paragraph is the actual reason why this is not included :)

**Comment by dkhunt27** [comment]
At first I thought it did the push (it was late last night HA), that is why I was wondering why not just do the push tags.  But since it doesn't do the push, makes sense.

Thanks for the grunt package, btw!
